### ISSUE TITLE
Submitting the pre-work!

### ISSUE THREAD

**Issue by neverbendeasy** [neverbendeasy/ToDoApp#1]
My app is complete, please review! @codepathreview @codepath

**Comment by nesquena** [comment]
Hi Erin,

Very nice to see the Parse integration and all around effort on this pre-work. I think you probably have a pretty good idea of what taking one of our classes is like so welcome to the class :)

**Comment by nesquena** [comment]
Also, to provide you a little bit of feedback, I'd encourage you to take a look at [this guide on code organization best practices](http://guides.codepath.com/android/Organizing-your-Source-Files) to cleanup the organization of your source code. In addition, right now the time is just a text field but I'd encourage you to experiment with [how to use a date picker](http://guides.codepath.com/android/Using-DialogFragment#displaying-date-or-time-picker-dialogs) instead.
